server:
  port: 8081
  servlet:
    context-path: /APIGateway  # Optional: Remove if not needed
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  redis:
    host: localhost
    port: 6379
  main:
    web-application-type: reactive
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/APIGateway/payment/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
      discovery:
         locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
