server:
  port: 8082
  servlet:
    context-path: /order
spring:
  application:
    name: order-service

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
